name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Seja bem-vindo ao repositorio, por favor, não dificulta as ações dos colaboradores!"
        pr-message: "Espere a permissão do Anfitrião"
